//go:build ignore

// Command iso3166gen regenerates engine/tables/country_data.go from
// engine/tables/generate/iso3166/alpha2.txt, one ISO 3166-1 alpha-2 code
// per line.
//
// # Provenance
//
// Unlike ISO 4217 (see engine/tables/generate/iso4217), the ISO 3166
// Maintenance Agency does not distribute a free, primary-source
// machine-readable list of alpha-2 codes -- ISO's own machine-readable
// products for 3166 are commercial. alpha2.txt was therefore compiled from
// two independently maintained secondary sources and accepted only because
// they agreed exactly, with zero discrepancies, on all 249 codes:
//
//  1. pycountry 26.2.16 (https://pypi.org/project/pycountry/), which
//     redistributes the Debian iso-codes project's ISO 3166-1 database.
//  2. the Open Knowledge Foundation's country-codes dataset
//     (https://github.com/datasets/country-codes/blob/master/data/country-codes.csv),
//     an independently compiled aggregation of ISO/UN/other official
//     sources.
//
// Both were fetched/queried on 2026-08-07. Regenerating alpha2.txt itself
// (as opposed to regenerating country_data.go from whatever alpha2.txt
// currently contains, which is all this program does) means re-running
// that two-source comparison and re-committing alpha2.txt only if it still
// agrees exactly; a disagreement between the two sources is a reason to
// investigate before updating anything, not to pick one arbitrarily.
//
// This program is excluded from the module's ordinary build, vet, lint, and
// coverage runs by the go:build tag above -- see the iso4217gen doc comment
// for why. Run it explicitly, from the repository root:
//
//	go run engine/tables/generate/iso3166/main.go
package main

import (
	"bufio"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"
)

const (
	sourcePath = "engine/tables/generate/iso3166/alpha2.txt"
	outputPath = "engine/tables/country_data.go"

	// version is the date the two-source cross-verification described in
	// this file's doc comment was performed. ISO 3166-1 alpha-2 has no
	// per-release version number of its own to report the way ISO 4217's
	// Pblshd date does -- ISO amends it via infrequent, individually
	// numbered Newsletters -- so this package reports the verification
	// date instead, which is exactly as auditable a claim: "this set of
	// codes was confirmed correct as of this date."
	version = "2026-08"
)

var alpha2Pattern = regexp.MustCompile(`^[A-Z]{2}$`)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "iso3166gen:", err)
		os.Exit(1)
	}
}

func run() error {
	codes, err := readCodes(sourcePath)
	if err != nil {
		return err
	}
	src, err := renderSource(codes)
	if err != nil {
		return err
	}
	if err := os.WriteFile(outputPath, src, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}
	fmt.Printf("iso3166gen: wrote %s (%d alpha-2 codes, version %s)\n", outputPath, len(codes), version)
	return nil
}

func readCodes(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	defer f.Close()

	seen := make(map[string]bool)
	var codes []string
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}
		if !alpha2Pattern.MatchString(line) {
			return nil, fmt.Errorf("%s: %q is not two uppercase ASCII letters", path, line)
		}
		if seen[line] {
			return nil, fmt.Errorf("%s: duplicate code %q", path, line)
		}
		seen[line] = true
		codes = append(codes, line)
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	sort.Strings(codes)
	return codes, nil
}

func renderSource(codes []string) ([]byte, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by `go run engine/tables/generate/iso3166/main.go`. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Source: engine/tables/generate/iso3166/alpha2.txt -- see that program's\n")
	fmt.Fprintf(&b, "// doc comment for the two-source provenance behind this list.\n")
	fmt.Fprintf(&b, "// %d ISO 3166-1 alpha-2 codes.\n", len(codes))
	fmt.Fprintf(&b, "package tables\n\n")
	fmt.Fprintf(&b, "// iso3166Version is the date the alpha-2 code list was last cross-verified\n")
	fmt.Fprintf(&b, "// against two independent sources -- see\n")
	fmt.Fprintf(&b, "// engine/tables/generate/iso3166/main.go's doc comment.\n")
	fmt.Fprintf(&b, "const iso3166Version = %q\n\n", version)
	fmt.Fprintf(&b, "// iso3166Alpha2Rows returns the compiled-in ISO 3166-1 alpha-2 country code\n")
	fmt.Fprintf(&b, "// list. It returns a fresh slice on every call rather than sharing one\n")
	fmt.Fprintf(&b, "// across calls, in keeping with this package holding no package-level\n")
	fmt.Fprintf(&b, "// state; NewISO3166Alpha2Table is the only intended caller.\n")
	fmt.Fprintf(&b, "func iso3166Alpha2Rows() []string {\n")
	fmt.Fprintf(&b, "\treturn []string{\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "\t\t%q,\n", c)
	}
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return formatted, nil
}
